// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZYkpo6IuG9rwKJG6GD-9lc2rg4uipJcc',
    appId: '1:238855831560:web:b1a5f638054cf2960ad1bd',
    messagingSenderId: '238855831560',
    projectId: 'firstflutter-4707c',
    authDomain: 'firstflutter-4707c.firebaseapp.com',
    storageBucket: 'firstflutter-4707c.firebasestorage.app',
    measurementId: 'G-W13GGGX3LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLYAAxdjQioB2YAudccRIZ-vt1H5vaypU',
    appId: '1:238855831560:android:a05d90bfe78ec2fb0ad1bd',
    messagingSenderId: '238855831560',
    projectId: 'firstflutter-4707c',
    storageBucket: 'firstflutter-4707c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfXvKmnK9Bfyl-ci-_G5qZY4mk6pNv9A',
    appId: '1:238855831560:ios:79c6f806f9ddf0760ad1bd',
    messagingSenderId: '238855831560',
    projectId: 'firstflutter-4707c',
    storageBucket: 'firstflutter-4707c.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfXvKmnK9Bfyl-ci-_G5qZY4mk6pNv9A',
    appId: '1:238855831560:ios:79c6f806f9ddf0760ad1bd',
    messagingSenderId: '238855831560',
    projectId: 'firstflutter-4707c',
    storageBucket: 'firstflutter-4707c.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutter',
  );
}
